# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Grocery.xcworkspace",
        scheme: "Pods-Grocery",
        export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "com.Melody-Yang.Grocery" => "ShareRecipe.mobileprovision"
      }
    }
    )
    upload_to_app_store
  end
end
